// src/App.tsx
import React from 'react';
import { BrowserRouter as Router, Switch, Route, Link } from 'react-router-dom'
import { Home, Login } from './pages'
import './App.css'

const App: React.FC = () => (
  <Router>
    <div>
      <nav>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/login">Login</Link></li>
        </ul>
      </nav>
      <Switch>
        <Route exact path='/' component={Home} />
        <Route path='/login' component={Login} />
      </Switch>
    </div>
  </Router>
)

export default App

// packages/web/src/App.svelte
<script>
  import { onMount } from 'svelte'
  import { Router, Link, Route, navigate } from 'svelte-routing'
  import Top from '@/pages/Top.svelte'
  import AuthenticatedRoute from '@/pages/AuthenticatedRoute.svelte'
</script>

<Router>
  <nav>
    <Link to="/">Home</Link>
    <Link to="/lobby">Login</Link>
  </nav>
  <div>
    <Route path="/" component="{Top}" />
    <Route path="/*" component="{AuthenticatedRoute}" />
  </div>
</Router>
